name: Publish package to the Maven Central Repository
on:
  release:
    types:
      - published
jobs:
  publish:
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v5
      with:
        distribution: 'adopt'
        java-version: 11
        server-id: 'ossrh'
        server-username: PUBLISHER_USERNAME
        server-password: PUBLISHER_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Get Maven project version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: Set Maven project version
      run: mvn versions:set -DnewVersion=$RELEASE_VERSION

    - name: Publish to Apache Maven Central
      run: mvn deploy
      env:
        PUBLISHER_USERNAME: ${{ secrets.PUBLISHER_USERNAME }}
        PUBLISHER_PASSWORD: ${{ secrets.PUBLISHER_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
